# Generated by Django 4.0 on 2022-01-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
