# Generated by Django 4.0 on 2022-01-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
